/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Report.java
 *
 * Created on Apr 23, 2013, 8:44:18 AM
 */
package reporttest;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.print.PrintService;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class Report extends javax.swing.JPanel {

    private DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    private String fileNamePath;
    private HashMap hashMap;
    private String[] headerReport;
    private PrintService printService;
    private ImageIcon logo;
    private String size;
    private boolean flagExtension;

    /** Creates new form Report */
    public Report() {
        initComponents();
    }

    public void setParameter(String... strings) {
        try {
            for (int i = 0; i < strings.length; i++) {
                String string = strings[i];
                System.out.println("----->String  " + string);

            }
            txtNguoiNopTien.setText(strings[0]);
            txtMaDuAn.setText(strings[1]);
            txtDiaChi.setText(strings[2]);
            txtSoDienThoai.setText(strings[3]);
            txtSanPhamDichVu.setText(strings[4]);
            txtTongTien.setText(strings[5]);
            txtBangChu.setText(strings[6]);
            txtNguoiPhuTrach.setText(strings[7]);
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }

    public void setPaperSize(String str) {
        this.size = str;
    }

    public void viewReport() {
        printReport(false);
    }

    public void printReport() {
        printReport(true);
    }

    public void setPrintService(PrintService printService) {
        this.printService = printService;
    }

    private void printReport(boolean view_print) {
        fileNamePath = getFileNamePath();
        String[] keys = new String[]{"prNguoiNopTien", "prMaDuAn", "prDiaChi", "prSoDienThoai", "prSanPhamDichVu", "prTongTien", "prBangChu", "prNguoiPhuTrach"};
        String[] values = new String[]{txtNguoiNopTien.getText(), txtMaDuAn.getText(), txtDiaChi.getText(), txtSoDienThoai.getText(), txtSanPhamDichVu.getText(), txtTongTien.getText(), txtBangChu.getText(), txtNguoiPhuTrach.getText()};
        System.out.println("----values---->" + values.toString());
        hashMap = new HashMap();
        if (keys.length == values.length) {
            for (int i = 0; i < keys.length; i++) {
                hashMap.put(keys[i], values[i]);
            }
        }
        reportExport(fileNamePath, hashMap,jTable1.getModel(), view_print);
    }

    public String getCodeReprotType() {
        return "Hóa đơn bán hàng";
    }

    private void reportExport(String filePathResource, HashMap hashMap, TableModel model, boolean view_print) {
        System.out.println("----->view-->"+view_print);
        if (!view_print) {
            ReportManager.getInstance().viewReport(filePathResource, hashMap,model, flagExtension);
        } else {
            ReportManager.getInstance().printReport(filePathResource, hashMap,model, printService, flagExtension);
        }
    }

    private String getFileNamePath() {
        String str = null;
        if (size.equals("A6")) {
            File file = HKTFile.getFile("TemplatePrint", "reportA6.jasper");
            if (file.exists()) {
                str = file.getAbsolutePath();
                flagExtension = true;
            } else {
                str = "D:/HKT/report/reporttest/report/reportA6.jasper";
                flagExtension = false;
            }
        }
        if (size.equals("A5")) {
            System.out.println("-----A5555");
            File file = HKTFile.getFile("TemplatePrint", "reportA5.jasper");
            if (file.exists()) {
                str = file.getAbsolutePath();
                flagExtension = true;
            } else {
                str = "C:/Users/Administrator.VIETFORUM/HKT SoftwareE nterprise Manager/TemplatePrint/reportA5.jasper";
                flagExtension = false;
            }
        }
        if (size.equals("K80")) {
            File file = HKTFile.getFile("TemplatePrint", "reportK80.jasper");
            if (file.exists()) {
                str = file.getAbsolutePath();
                flagExtension = true;
            } else {
                str = "D:/HKT/report/reporttest/report/reportK80.jasper";
                flagExtension = false;
            }
        }
        return str;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSanPhamDichVu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaDuAn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNguoiPhuTrach = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBangChu = new javax.swing.JTextField();
        txtNguoiNopTien = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbNgay = new javax.swing.JLabel();
        lbThang = new javax.swing.JLabel();
        lbNam = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Họ và tên người nộp tiền :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("PHIẾU THU");

        jLabel10.setText("Sản phẩm dịch vụ :");

        jLabel2.setText("PGD: Phòng D1 - Tầng 9 - 335 Cầu Giấy - HN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CÔNG TY CỔ PHẦN TƯ VẤN QUẢN TRỊ HKT");

        jLabel9.setText("Số điện thoại :");

        jLabel4.setText("Email: hkt@gmail.com");

        jLabel3.setText("Website: www.hktconsultant.com");

        jLabel13.setText("Người phụ trách :");

        jLabel7.setText("Mã dự án :");

        jLabel12.setText("Bằng chữ :");

        jLabel8.setText("Địa chỉ :");

        jLabel11.setText("Tổng tiền :");

        jLabel14.setText("PT: Số......../2013/HKT");

        jLabel15.setText("Nợ:........................");

        jLabel16.setText("Lập phiếu");

        jLabel17.setText("Người nộp tiền");

        jLabel18.setText("Giám đốc");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel19.setText("Ngày :");

        jLabel20.setText("Tháng :");

        jLabel21.setText("Năm :");

        lbNgay.setText("lbNgay");

        lbThang.setText("lbThang");

        lbNam.setText("lbNam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(txtMaDuAn, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(txtNguoiNopTien, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(txtSanPhamDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(txtBangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addComponent(txtNguoiPhuTrach, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(213, 213, 213)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                                .addComponent(jLabel18)))))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel19)
                .addGap(5, 5, 5)
                .addComponent(lbNgay)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(2, 2, 2)
                .addComponent(lbThang)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNam)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(lbNgay)
                    .addComponent(lbThang)
                    .addComponent(lbNam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNguoiNopTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMaDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSanPhamDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNguoiPhuTrach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbNam;
    private javax.swing.JLabel lbNgay;
    private javax.swing.JLabel lbThang;
    private javax.swing.JTextField txtBangChu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaDuAn;
    private javax.swing.JTextField txtNguoiNopTien;
    private javax.swing.JTextField txtNguoiPhuTrach;
    private javax.swing.JTextField txtSanPhamDichVu;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
